server:
  port: 8081
spring:
  application:
    name: "JavaMqResponse"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    include: null
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
commons:
  jms:
    input-concurrency: 10
    input-queue: "DEV.QUEUE.2"
    input-queue-alias: ""
    reactive: true
    output-concurrency: 10
    output-queue: "DEV.QUEUE.1"
    producer-ttl: 0
ibm:
  mq:
    conn-name: "${MQ_RESPONSE_HOST:127.0.0.1(1414)}"
    channel: "DEV.APP.SVRCONN"
    user: "app"
    password: "passw0rd"
mq-response:
  delay: ${MQ_RESPONSE_DELAY:0}